FPS = 60

# UI
UI_FONT = './graphics/fonts/LiberationMono-Bold.ttf'
UI_FONT_SIZE = 42
TEXT_COLOR = '#EEEEEE'
UI_BG_COLOR = '#222222'
UI_BORDER_COLOR = '#FFFFFF'
TRANSITION_COLOR = '#404040'

LAW_SHEET_TEXT_COLOR = '#000000'
TIME_GAUGE_COLOR = '#999999'
CAM_NO_TEXT_COLOR = '#00ff17'

WIDTH = 1280
HEIGHT = 720
SCALE_FACTOR = 1

# Message boxes
TEXT_SPEED = .15
MESSAGE_BOX_X = 0 
MESSAGE_BOX_Y = HEIGHT * 0.8
MESSAGE_BOX_WIDTH = WIDTH
MESSAGE_BOX_HEIGHT = HEIGHT * 0.2
MAX_CHAR_PER_LINE = 60
MARGIN = 16


TRANSITION_MODE_IN = 0
TRANSITION_MODE_OUT = 1

# Player
PLAYER_SPEED = 5

# Day
HOUR_LENGTH = 7500
NUMBER_OF_DAYS = 5

# INTERACTIONS
ACTIVATION_MARGIN = 50
POLICE_BUTTON_X = 275
CAM_BUTTON_X = 470
PAPERS_X = 705

# CAMERAS
NUMBER_OF_CAMERAS = 4

# LAW CODES
LAW_NO_MUSIC = 0
LAW_NO_OPENED_WINDOW = 1
LAW_LIGHTS_ALWAYS_ON = 2
LAW_DONT_STOP_MOVING = 3
LAW_NO_VISIT_OTHER_SPECIES = 4
LAW_NO_VISIT_SAME_SPECIES = 5

# INFRACTIONS
INFRACTION_PROBABILITY = 0.9
BAD_BEHAVIOR_DURATION = HOUR_LENGTH
BAD_ARREST_PENALTY = 250
GOOD_ARREST_BONUS = 250