FPS = 60

# UI
UI_FONT = './graphics/fonts/LiberationMono-Bold.ttf'
UI_FONT_SIZE = 42
TEXT_COLOR = '#EEEEEE'
UI_BG_COLOR = '#222222'
UI_BORDER_COLOR = '#FFFFFF'
TRANSITION_COLOR = '#404040'

WIDTH = 1920
HEIGHT = 1024
SCALE_FACTOR = 1

# Message boxes
TEXT_SPEED = .15
MESSAGE_BOX_X = 0 
MESSAGE_BOX_Y = HEIGHT * 0.8
MESSAGE_BOX_WIDTH = WIDTH
MESSAGE_BOX_HEIGHT = HEIGHT * 0.2
MAX_CHAR_PER_LINE = 20
MARGIN = 16


TRANSITION_MODE_IN = 0
TRANSITION_MODE_OUT = 1

# Player
PLAYER_SPEED = 5

# INTERACTIONS
POLICE_BUTTON_X = 535
CAM_BUTTON_X = 705
PAPERS_X = 945

# CAMERAS
NUMBER_OF_CAMERAS = 4
